name: Trigger Mirror Workflow

on:
  workflow_dispatch:

jobs:
  trigger-mirror:
    uses: org-name/repo-name/.github/workflows/mirror-repo.yml@main
    with:
      bitbucket_repo_url: "bitbucket.org/workspace-name/repo-name"
      github_repo_name: "repo-name"
      github_org_name: "github-org"
      github_token: ${{ secrets.GITHUB_PAT }}
      bitbucket_username: ${{ secrets.BITBUCKET_USERNAME }}
      bitbucket_app_password: ${{ secrets.BITBUCKET_APP_PASSWORD }}
